#!/bin/bash
## Manual MongoDB Start
mongod --config /etc/mongod.conf &
##mongod &

## Test
##mongo --port 27017

## Service Start
## service mongod start

## Service Stop 
## service mongod stop

## Service Restart 
## service mongod restart

## Set to autostart at boot
##  chkconfig mongod on 
